<a href="https://colab.research.google.com/github/Khaled-844AI/Pytorch00_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd


In [ ]:
scaler = torch.tensor(7)
scaler
#tensors have no dementions

tensor(7)

In [ ]:
scaler.item()
#get tensor back in int format

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector
vector.ndim#demention

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7, 8],[10, 9]])
MATRIX


tensor([[ 7,  8],
        [10,  9]])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 5, 9],
                        [4, 8, 7],
                        [9, 10, 5]]])
TENSOR

tensor([[[ 1,  5,  9],
         [ 4,  8,  7],
         [ 9, 10,  5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
### RANDOM TENSORS
#why?

#Random ransors important because the way many neural networks learn is that they start with tensors full of random numbers
#and then they adjust this numbers to better represent the data
#Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
#Create a random tensor of size {3, 4}
Random_tensor = torch.rand(3, 4)#3Dementions
Random_tensor

tensor([[0.9421, 0.3501, 0.3594, 0.6288],
        [0.5241, 0.6105, 0.7341, 0.3783],
        [0.9658, 0.2242, 0.6918, 0.1490]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tesor = torch.rand(size=(224, 224, 3))#height, width, color channel
random_image_size_tesor.ndim,random_image_size_tesor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
#my own random tensor
My_Tensor = torch.rand(size=(4, 255, 255))
My_Tensor

tensor([[[0.0127, 0.3577, 0.3134,  ..., 0.3318, 0.2530, 0.7240],
         [0.0410, 0.3789, 0.1905,  ..., 0.0527, 0.4841, 0.2253],
         [0.0478, 0.2854, 0.4340,  ..., 0.4449, 0.9518, 0.4929],
         ...,
         [0.2407, 0.0279, 0.9086,  ..., 0.9927, 0.1115, 0.9695],
         [0.1294, 0.1562, 0.2718,  ..., 0.8255, 0.9577, 0.4954],
         [0.6541, 0.9487, 0.0337,  ..., 0.4183, 0.6668, 0.4979]],

        [[0.4766, 0.0713, 0.3646,  ..., 0.7426, 0.0625, 0.5422],
         [0.4596, 0.7811, 0.3735,  ..., 0.0197, 0.7275, 0.6558],
         [0.5011, 0.0307, 0.6962,  ..., 0.4823, 0.0729, 0.0264],
         ...,
         [0.0294, 0.5822, 0.0832,  ..., 0.6498, 0.2211, 0.9394],
         [0.2666, 0.1617, 0.4877,  ..., 0.4998, 0.8065, 0.5182],
         [0.1138, 0.8630, 0.4442,  ..., 0.8291, 0.7531, 0.8754]],

        [[0.8132, 0.2049, 0.0190,  ..., 0.7454, 0.9029, 0.1891],
         [0.7884, 0.7425, 0.6635,  ..., 0.3941, 0.8563, 0.7282],
         [0.9421, 0.8296, 0.8190,  ..., 0.9995, 0.2935, 0.

In [ ]:
My_Tensor.ndim

3

In [ ]:
#Create tensor of all zeros 
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*Random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__#to check the torch version

'1.13.1+cu116'

In [ ]:
range = torch.arange(start=0, end=1001, step=50)
range

tensor([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
         600,  650,  700,  750,  800,  850,  900,  950, 1000])

In [ ]:
#Creating tensors like
range_like = torch.zeros_like(input=range)
range_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Note**:tensor datatypes is one of 3 big errors you ll run into with pytorch & deep learning : 

    1. Tensors not right datatype
    2. Tensors not right shape
    3. Tensors not on the right device


In [ ]:
#float 32 tesor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,#data type 32 bit or 64 bit or 16 bit
                               device="cpu",#the device type cpu or gpu (cuda)
                               requires_grad=False)# wether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype #even we set it ti none in pytorch it s gona be float 32 by default

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)#or we can use .half to convert from 32 to 16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#tensor multiplication

tensor = torch.tensor([1,2,3])
print(tensor,"*",tensor,"=",tensor*tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor


tensor(14)

In [ ]:
torch.rand(3 , 2) @ torch.rand(2 , 3)

tensor([[0.4997, 0.2502, 0.6177],
        [0.6562, 0.3462, 0.8265],
        [0.7969, 0.0954, 0.7198]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**,wich stands for switching the axes of a given tensor

In [ ]:
tensor_A = torch.rand(3,4)
tensor_A

tensor([[0.8637, 0.1965, 0.1355, 0.8359],
        [0.4539, 0.2912, 0.0520, 0.4054],
        [0.5856, 0.8401, 0.2966, 0.3176]])

In [ ]:
tensor_B = torch.rand(3,4)
tensor_B

tensor([[0.7289, 0.9765, 0.0763, 0.2041],
        [0.9618, 0.7068, 0.1048, 0.7257],
        [0.0856, 0.7133, 0.0864, 0.6776]])

In [ ]:
tensor_A @ tensor_B.T

tensor([[1.0024, 1.5905, 0.7922],
        [0.7019, 0.9420, 0.5257],
        [1.3346, 1.4186, 0.8902]])

In [ ]:
#Tensor agregation (finding min , max , mean , sum ...)
x = torch.arange(0 , 100 , 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:

torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the mean
torch.mean(x)

RuntimeError: ignored

In [ ]:
#To fix the error 
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Finding the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [ ]:
#The index of the min
x.argmin()

tensor(0)

In [ ]:
#finding the index of the max
x.argmax()

tensor(9)

In [ ]:
# Rechaping , stacking , squeezing and unsqueezing tensors
z = torch.arange(1., 10.)
z,z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an exetra dimention
x_reshaped = z.reshape(1, 9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view (the difference between view and reshape is that view changes also the original tensor z and also y)
y= z.view(1 , 9)
y, y.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[0]= 5
z , y

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
# stack tensors on top of each other
Y_stacked = torch.stack([y, y, y, y], dim = 1)
Y_stacked 

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
V_stacked = torch.hstack([y,y,y,y])
V_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
c= torch.ones(3 , 4)
c ,c.squeeze()

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), None, tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
#torch.permute - rearanges the dimentions of a target tensor to a specified order and returns a view(it changes the original tensor)
w = torch.randn(2, 3 ,5)
w

tensor([[[ 0.6292, -1.9772,  0.2703, -0.6820,  2.3985],
         [-0.9666,  0.9475,  0.5945,  0.2390,  1.5234],
         [ 0.0497,  0.7633,  0.2591,  0.0454, -0.0556]],

        [[ 0.8556,  1.3126,  0.4669, -1.9948, -0.9489],
         [ 1.6336, -1.8352,  1.2399,  0.1453,  0.1050],
         [-0.0648,  1.2530, -1.3577, -0.4159,  0.6499]]])

In [ ]:
torch.permute(w,(0,1,2))

tensor([[[ 0.6292, -1.9772,  0.2703, -0.6820,  2.3985],
         [-0.9666,  0.9475,  0.5945,  0.2390,  1.5234],
         [ 0.0497,  0.7633,  0.2591,  0.0454, -0.0556]],

        [[ 0.8556,  1.3126,  0.4669, -1.9948, -0.9489],
         [ 1.6336, -1.8352,  1.2399,  0.1453,  0.1050],
         [-0.0648,  1.2530, -1.3577, -0.4159,  0.6499]]])

In [ ]:
#in most cases we use permute for images
image = torch.rand(size = (10,10,4)) #[height , width , colorchannel]
image

tensor([[[6.6250e-01, 2.0093e-01, 3.5667e-02, 7.9474e-01],
         [4.6465e-01, 1.0536e-01, 1.9341e-01, 2.5020e-01],
         [5.7771e-01, 3.2522e-02, 1.1780e-01, 9.4201e-01],
         [6.0058e-01, 8.8613e-01, 7.7818e-01, 1.1768e-01],
         [7.9182e-01, 5.7324e-01, 2.9960e-01, 3.6397e-01],
         [6.9371e-01, 4.0266e-01, 3.1925e-01, 3.7561e-01],
         [6.1500e-01, 9.5491e-01, 5.8818e-01, 8.5969e-01],
         [8.0116e-01, 7.0151e-01, 3.4638e-01, 8.9902e-01],
         [9.2398e-01, 9.1987e-01, 6.0371e-01, 2.0786e-01],
         [1.4792e-01, 6.3028e-01, 4.6472e-01, 6.9630e-01]],

        [[3.9407e-01, 4.1737e-01, 3.9036e-01, 7.9939e-01],
         [2.7513e-01, 3.8367e-01, 6.8434e-02, 5.5842e-01],
         [4.8886e-01, 4.2740e-01, 4.4996e-01, 3.0502e-01],
         [7.0183e-03, 3.3076e-01, 3.4180e-01, 2.6243e-02],
         [4.8303e-01, 3.7492e-01, 8.9672e-01, 4.3049e-01],
         [3.1361e-01, 3.3745e-01, 4.7434e-01, 2.1822e-01],
         [5.8761e-02, 9.5214e-01, 1.3045e-01, 8.3618e-

In [ ]:
print(f"New tensor :{torch.permute(image,(2,0,1))}") # [colorchannel , height , width]
image_like = torch.permute(image, (2,0,1))


New tensor :tensor([[[4.4570e+03, 8.1537e-01, 8.7327e-01, 2.9272e-02, 9.9845e-01,
          3.7422e-01, 7.4490e-02, 6.7975e-01, 1.4583e-01, 4.0319e-01],
         [4.7794e-01, 6.0654e-01, 9.8630e-01, 2.2531e-01, 4.5468e-01,
          8.3314e-01, 8.0542e-01, 7.9028e-01, 4.8884e-01, 5.2383e-01],
         [6.7937e-01, 1.1524e-01, 5.0156e-01, 5.5607e-01, 4.6660e-01,
          3.4624e-01, 2.9446e-01, 3.3702e-01, 8.2228e-01, 3.1883e-02],
         [5.4678e-01, 3.1739e-01, 4.4523e-01, 2.3167e-01, 4.4680e-01,
          1.5436e-01, 4.3995e-01, 2.4884e-01, 4.1933e-01, 5.7205e-01],
         [3.1308e-01, 4.8334e-01, 1.3092e-01, 8.4896e-01, 8.6183e-01,
          1.7503e-01, 3.7190e-01, 4.1263e-01, 6.1130e-01, 8.5711e-01],
         [8.0497e-01, 5.0129e-01, 6.4639e-01, 3.2145e-01, 2.1716e-01,
          7.8772e-01, 6.6041e-01, 9.0028e-01, 8.6488e-01, 9.2420e-01],
         [7.8709e-01, 6.7448e-03, 1.7040e-01, 3.1379e-02, 2.1421e-02,
          6.6741e-01, 5.1501e-01, 2.2545e-01, 2.0193e-01, 7.3470e-01],
 

In [ ]:
image[0, 0 ,0] = 4457
image[0,0,0], image_like[0,0,0]

(tensor(4457.), tensor(4457.))

#- Indexing in pytorch(selecting Data from tensor): 
*indexing with pytorch is similar to indexing with NumPy.

In [ ]:
#Creating a tensor
import torch
x = torch.arange(1,10).reshape(1, 3 , 3) # [ outer bracket , lines , colones]
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
#Changing index 
x[0,1] = 2
x

tensor([[[1, 2, 3],
         [2, 2, 2],
         [7, 8, 9]]])

In [ ]:
# you can also use ":" to select "all" of a target dimentions
x[:,0]=2
x

tensor([[[2, 2, 2],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Gett all values of 0th dimentions but only index 1 of 2nd dimention
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
#Pytorch tensors && Numpy


Numpy is numerical computing library in python
* Data in Numpy , Want in pytorch tensor -> 'torch.from_numpy(ndarray)'
* Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
#warning when converting from numpy -> pytorch , pytorch rflects numpy s default datatype to float 64
array , tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
#change the value of array

array = array + 1

array , tensor


(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the value of tensor 
tensor = tensor +1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
 #random in neural networks

torch.rand(3, 3)


tensor([[0.3289, 0.7533, 0.0780],
        [0.8922, 0.8814, 0.9561],
        [0.4983, 0.5858, 0.2260]])

In [ ]:
#to reduce the randomness

import torch

random1 =  torch.rand(3,4)
random2 =  torch.rand(3,4)

print(random1)
print(random2)
print(random1 == random2)

tensor([[0.2717, 0.4412, 0.6021, 0.0097],
        [0.8714, 0.1693, 0.1106, 0.4424],
        [0.8026, 0.2708, 0.2153, 0.6208]])
tensor([[0.0329, 0.1659, 0.3566, 0.7377],
        [0.8702, 0.1430, 0.4212, 0.4178],
        [0.1727, 0.5044, 0.6348, 0.0654]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#making some randome but producable tensors

#set the random seeds

random_seed = 0
torch.manual_seed(random_seed) # to fix the randomness
random_tensor1 = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor2 = torch.rand(3, 4)

print(random_tensor1)
print(random_tensor2)
print(random_tensor1 == random_tensor2)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#Running tensors on GPU s

#1. getting GPU

# use google collabe for free GPU

!nvidia-smi

Sat Mar 18 21:08:13 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    31W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# check for GPU access Pytorch
import torch
torch.cuda.is_available()



True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

In [ ]:
# putting tensors and models on the GPU

tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU if available

tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# moving tensors back to the cpu

#if tensors are on the GPU we can t transform to Numpy
tensor_on_GPU.numpy()

TypeError: ignored

In [ ]:
# to fix it we set it first to the cpu

tensor_back_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

In [ ]:
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# EXERCICES

tensor = torch.rand([7 ,7])

tensor1 = torch.rand([7 , 1])
tensor , tensor1

(tensor([[0.8719, 0.3419, 0.4765, 0.8277, 0.8240, 0.4632, 0.9399],
         [0.5137, 0.6325, 0.5086, 0.8740, 0.2669, 0.5713, 0.4915],
         [0.5203, 0.5797, 0.1095, 0.4481, 0.7299, 0.3923, 0.7946],
         [0.0974, 0.0175, 0.4711, 0.9799, 0.1929, 0.5352, 0.2786],
         [0.9135, 0.3820, 0.2492, 0.3045, 0.6927, 0.8004, 0.6620],
         [0.1004, 0.9946, 0.2981, 0.6582, 0.1200, 0.3667, 0.3211],
         [0.6610, 0.6949, 0.5942, 0.6133, 0.1046, 0.5059, 0.0626]]),
 tensor([[0.0685],
         [0.2262],
         [0.4684],
         [0.9764],
         [0.9941],
         [0.6571],
         [0.0833]]))

In [ ]:
tensor @ tensor1

tensor([[2.3702],
        [1.9515],
        [1.7051],
        [1.7547],
        [1.8327],
        [1.4011],
        [1.5211]])

In [ ]:
Random_seed = 0
torch.manual_seed(Random_seed)
rtensor1 = torch.rand([ 7 , 7])
Random_seed = 0
torch.manual_seed(Random_seed)
rtensor2 = torch.rand([ 7 , 1])
print(rtensor1)
print(rtensor2)
print(rtensor1[0] == rtensor2[: , 0])

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
tensor([True, True, True, True, True, True, True])


In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "CPU"
device

'cuda'

In [ ]:
tensor1 = torch.rand(size=( 2 , 3)).to(device)
tensor2 = torch.rand(size=( 2 , 3)).to(device)

print(tensor1,device)
print(tensor2,device)

tensor([[0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223]], device='cuda:0') cuda
tensor([[0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610]], device='cuda:0') cuda


In [ ]:
tensor1 @ tensor2.T

tensor([[0.6131, 1.0917],
        [0.1886, 0.5684]], device='cuda:0')

In [ ]:
max = torch.max(tensor1 @ tensor2.T)
min = torch.min(tensor1 @ tensor2.T)
print(max)
print(min)

tensor(1.0917, device='cuda:0')
tensor(0.1886, device='cuda:0')


In [ ]:
torch.manual_seed(7)

tensor3 = torch.rand(size=(1,1,1,10))
tensor3.squeeze()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])